name: Packer Build

on:
  push:
    branches:
      - development 

jobs:
  packer-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Packer
      uses: hashicorp/setup-packer@v3
      with:
        version: latest

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.DEV_AWS_REGION }}

    - name: Validate Packer template
      run: packer validate -var-file=development.vars.hcl .
      working-directory: ./packer/

    - name: Build Packer image
      run: packer build -var-file=development.vars.hcl .
      working-directory: ./packer/